Lesson 10
Chistyakov-AY/ror_test-guru pull request #13
Opened 2024-02-15 11:05 UTC by Chistyakov-AY

1. Добавьте в сессию идентификатор пользователя после его регистрации
2. Создайте хэлпер для flash сообщений
3. Реализуйте выход пользователя из системы
4. Создайте навигацию с названием проекта и ссылками для регистрации/логина/выхода пользователя. Если пользователь находится в системе - выводить сообщение Welcome, <user name> Guru. Название проекта должно быть ссылкой и вести на главную страницу приложения.
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально
7. Проверяйте формат и уникальность атрибута email для пользователя
8. Используйте объект текущего пользователя при старте прохождения теста

2024-02-15 19:21 UTC, BubuntuClu requested changes

2024-02-15 19:21 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    unless current_user
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально

не сделал этот пункт

2024-02-15 19:21 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  def flash_messages
возожно стоит вынести в отдельный файл, чтобы не смешивать логику всех хэлперов в одном месте

у тебя сейчас выводится только флэш с ключом алертом, но ключей у тебя может быть много. надо написать код, который будет выводить все ключи

2024-02-15 19:21 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
это роуты дубли

2024-02-15 19:21 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email"
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2024-02-19 17:32 UTC, BubuntuClu commented on app/views/shared/_flash.html.erb
> +<% flash.each do |type, message| %>
по коду норм, только это не хэлпер у тебя, а паршиал. по условию задачи нужно сделать все-таки хэлпер

2024-02-20 16:55 UTC, merged

2024-06-01 16:17 UTC, Chistyakov-AY commented on config/routes.rb
> +  get 'users/new'
убрал

2024-06-01 16:17 UTC, Chistyakov-AY commented on app/helpers/application_helper.rb
> +  def flash_messages
реализовал через паршл _flash.html.erb

2024-06-01 16:17 UTC, Chistyakov-AY commented on db/schema.rb
>      t.string "email"
добавил

2024-06-01 16:17 UTC, Chistyakov-AY commented on app/controllers/application_controller.rb
> +    unless current_user
дописал

2024-06-01 16:17 UTC, Chistyakov-AY commented on app/views/shared/_flash.html.erb
> +<% flash.each do |type, message| %>
сделал