Revert "Revert "Lesson 13""
Chistyakov-AY/ror_test-guru pull request #18
Opened 2024-05-03 17:17 UTC by Chistyakov-AY

Смержил с 13 уроком, откатил для проверки
Reverts Chistyakov-AY/ror_test-guru#17

2024-05-03 17:33 UTC, BubuntuClu requested changes

2024-05-03 17:33 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    service = GistQuestionService.new(@test_passage.current_question, client:)
`client: client` давай явно передавать параметры. так понятней что проихсодит, не надо лишний раз напрягать мозг)

2024-05-03 17:33 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +  before_action :set_test_passage, only: %i[create]
зачем колбэке на один метод? ты так больше кода пишешь

2024-05-03 17:33 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :set_test_passage, only: %i[show update result gist]
тут надо удалить несущетвующий экшн

2024-05-03 17:33 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :questions, through: :gists, dependent: :destroy
точно нужна опция на удаление?

2024-05-03 17:33 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @client.last_response.status == 201
если тут в клиенте будет гитхабклиент, то код упадет. гитхаб клиент не знает что за метод `last_response`. тут надо еще добавить вложенность и перенести реализацию проверки успеха в сами клиенты. 

```
def success?
  @client.success?
end
```

и уже в каждом клиенте реализовывать метод 
`def success?`

2024-05-03 17:33 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +      redirect_to @test_passage, notice: t('.success', url: result[:html_url]).html_safe
давай сначала сделаем все манипуляции, а потом редирект оформим

2024-05-03 17:33 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +      Gist.create(user_id: current_user.id, question_id: @test_passage.current_question.id, url: result[:html_url].html_safe)
можно через ассоциации создать `current_user.gists.create` - чуть короче будет

2024-05-03 19:12 UTC, Chistyakov-AY commented on app/controllers/gists_controller.rb
> +    service = GistQuestionService.new(@test_passage.current_question, client:)
ок

2024-05-03 19:15 UTC, Chistyakov-AY commented on app/controllers/gists_controller.rb
> +  before_action :set_test_passage, only: %i[create]
согласен, переделал

2024-05-03 19:16 UTC, Chistyakov-AY commented on app/controllers/test_passages_controller.rb
> +  before_action :set_test_passage, only: %i[show update result gist]
удалил

2024-05-05 07:28 UTC, Chistyakov-AY commented on app/models/user.rb
> +  has_many :questions, through: :gists, dependent: :destroy
не нужна, удалил

2024-05-05 14:18 UTC, Chistyakov-AY commented on app/services/gist_question_service.rb
> +    @client.last_response.status == 201
сделал

2024-05-05 14:18 UTC, Chistyakov-AY commented on app/controllers/gists_controller.rb
> +      redirect_to @test_passage, notice: t('.success', url: result[:html_url]).html_safe
ок

2024-05-05 14:19 UTC, Chistyakov-AY commented on app/controllers/gists_controller.rb
> +    service = GistQuestionService.new(@test_passage.current_question, client:)
переделал

2024-05-05 17:55 UTC, Chistyakov-AY commented on app/controllers/gists_controller.rb
> +      Gist.create(user_id: current_user.id, question_id: @test_passage.current_question.id, url: result[:html_url].html_safe)
сделал

2024-05-07 08:30 UTC, merged