Lesson6
Chistyakov-AY/ror_test-guru pull request #7
Opened 2023-11-29 12:53 UTC by Chistyakov-AY

1. Определите scope-методы:
для выбора правильных Ответов
Для выбора Тестов по уровню сложности:
  простой (нулевой или первый уровень),
       средний (со второго по четвёртый),
       сложный (с пятого и выше). Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания

2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях

3. Определите валидации данных:
Наличие атрибутов title, body, email в соответствующих моделях
Уровень Теста может быть только положительным целым числом
Может существовать только один Тест с данным названием и уровнем
У одного Вопроса может быть от 1-го до 4-х ответов.

2023-11-29 18:45 UTC, BubuntuClu requested changes

2023-11-29 18:45 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :simple_tests, -> {where(level: 0..1)}
эти скоупы можно переписать с использованием скоупа `list_of_level_tests`

2023-11-29 18:45 UTC, BubuntuClu commented on app/models/user.rb
> +    author_tests.list_of_level_tests(level)
author_tests - тут использовать эту ассоциацию неправильно.
ты понимаешь в чем разница между `author_tests` и `tests`?

2023-11-29 18:45 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level}
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2023-11-30 09:56 UTC, Chistyakov-AY commented on app/models/user.rb
> +    author_tests.list_of_level_tests(level)
author_tests связь напрямую с таблицей users, а tests связь с users через таблицу test_users.

2023-11-30 09:59 UTC, Chistyakov-AY commented on app/models/user.rb
> +    author_tests.list_of_level_tests(level)
согласен, исправил

2023-11-30 10:08 UTC, Chistyakov-AY commented on app/models/test.rb
> +  scope :simple_tests, -> {where(level: 0..1)}
переписал

2023-11-30 10:09 UTC, Chistyakov-AY commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level}
добавил миграцию в таблицу tests

2023-11-30 18:06 UTC, merged